repos:
-   repo: local
    hooks:
    -   id: custom-json-check
        name: Custom JSON Validator
        entry: scripts/validate-json.sh
        language: script
        files: \.json$

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
